create database prd_thuisadmin;
create user prd_thuisadmin;
grant all on prd_thuisadmin.* to 'prd_thuisadmin'@'localhost' identified by 'pcat3900';
grant select, insert, delete on tst_thuisadmin.* to 'prd_thuisadmin'@'localhost' identified by 'pcat3900';

CREATE TABLE TA_PERSONEN(
    PK_ID BIGINT NOT NULL,
    NAAM VARCHAR(255) NOT NULL,
    VOORNAAM VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    MD5_PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (PK_ID));

CREATE TABLE TA_TYPE_GROEP(
    PK_ID BIGINT NOT NULL,
    FK_HOOFD_TYPE_GROEP_ID BIGINT,
    FK_PERSONEN_ID BIGINT NOT NULL,
    NAAM VARCHAR(255) NOT NULL,
    OMSCHRIJVING VARCHAR(4000),
    NEGATIEF INT NOT NULL,
    CODE_ID VARCHAR(50),
    PUBLIC_GROEP INT,
    PRIMARY KEY (PK_ID));

CREATE TABLE TA_REKENINGEN(
    PK_ID BIGINT NOT NULL,
    FK_PERSONEN_ID BIGINT NOT NULL,
    NAAM VARCHAR(255) NOT NULL,
    WAARDE DECIMAL(9,2) NOT NULL,
    LAATST_BIJGEWERKT DATE NOT NULL,
    PRIMARY KEY (PK_ID));

CREATE TABLE TA_BEDRAGEN(
    PK_ID BIGINT NOT NULL,
    FK_PERSOON_ID BIGINT NOT NULL,
    FK_REKENING_ID BIGINT NOT NULL,
    FK_TYPE_GROEP_ID BIGINT NOT NULL,
    BEDRAG DECIMAL(9,2) NOT NULL,
    OMSCHRIJVING VARCHAR(4000),
    DATUM DATE NOT NULL,
    PRIMARY KEY (PK_ID));

CREATE TABLE TA_BEDRAG_DOCUMENTEN(
    PK_ID BIGINT NOT NULL,
    FK_BEDRAG_ID BIGINT NOT NULL,
    OMSCHRIJVING VARCHAR(4000),
    DOCUMENT MEDIUMBLOB,
    DOCUMENT_MIME VARCHAR(255) NOT NULL,
    DOCUMENT_NAAM VARCHAR(255) NOT NULL,
    PRIMARY KEY (PK_ID));
